version: '3'
services:
  webserver:
    image: labexer:latest
    
    volumes:
      - .:/opt/airflow/dags
      - ./includes:/opt/airflow/includes
      - ./logs:/opt/airflow/logs
      - ./includes/json_files/customer_transaction_info.json:/opt/airflow/customer_transaction_info.json
      - ./includes/json_files/branch_service_transaction_info.json:/opt/airflow/branch_service_transaction_info.json
      - ./includes/airflow-db:/opt/airflow/airflow-db

    ports:
      - "8080:8080"
    command: airflow standalone
